FROM golang:1.24

ENV CGO_ENABLED=0

EXPOSE 9090 2345

COPY . /go/src

COPY config.yaml /var/run

WORKDIR /go/src

RUN \
  go build -gcflags "all=-N -l" -o /bin/echoctl ./cli && \
  go install github.com/go-delve/delve/cmd/dlv@v1.24.0

ENTRYPOINT ["/go/bin/dlv", "--listen=:2345", "--headless=true", "--api-version=2", "--accept-multiclient", "--log", "--log-output=rpc,dap,debugger,gdbwire", "exec", "/bin/echoctl", "--continue", "--", "server", "--config=/var/run/config.yaml"]
